### ISSUE TITLE
FF 28.0 TypeError: o[p] is not a function. iframeResizer.contentWindow

### ISSUE THREAD

**Issue by BlastingKap** [davidjbradshaw/iframe-resizer#29]
Happens only FF since updating from the previous version to 2.3. I haven't tried it with any earlier versions of FF. Error message pops up regardless of the heightCalculationMethod. I also have sizeWidth enabled.

Chrome and IE looking fine, really appreciate the update!
