### ISSUE TITLE
TypeScript error in iframe-resizer.parent.d.ts

### ISSUE THREAD

**Issue by snelle18** [davidjbradshaw/iframe-resizer#1473]
TypeScript error: c:/src/x/node_modules/@iframe-resizer/parent/iframe-resizer.parent.d.ts(188,12): Error TS2304: Cannot find name 'IFrameComponent'.
    at formatError (C:\src\x\node_modules\gulp-cli\lib\versioned\^4.0.0\format-error.js:21:10)
    at Gulp.<anonymous> (C:\src\x\node_modules\gulp-cli\lib\versioned\^4.0.0\log\events.js:33:15)
    at Gulp.emit (node:events:530:35)
    at Gulp.emit (node:domain:489:12)
    at Object.error (C:\src\x\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (C:\src\x\node_modules\now-and-later\lib\map.js:50:14)
    at f (C:\src\x\node_modules\once\once.js:25:25)
    at f (C:\src\x\node_modules\once\once.js:25:25)
    at tryCatch (C:\src\x\node_modules\async-done\index.js:24:15)
    at done (C:\src\x\node_modules\async-done\index.js:40:12)

When trying to build we get above exception. 

<img width="617" height="766" alt="Image" src="https://github.com/user-attachments/assets/f7612ccd-288f-475d-8b3c-9b4e88f03f41" />

Also when inspecting the definition in VSCode there are warnings.

These errors appear when updating from 5.3.2 to 5.4.7.

**Comment by davidjbradshaw** [comment]
That's very strange, as it is defined on line 28

https://github.com/davidjbradshaw/iframe-resizer/blob/0766e5cd2fc56b39682f297b9b27154e87412b99/packages/parent/index.d.ts#L28

Do you have the same issue on 5.4.6?

**Comment by davidjbradshaw** [comment]
Digging a little deeper this line was added by a submitted PR back in February and I don't really see why. 

https://github.com/davidjbradshaw/iframe-resizer/blob/0766e5cd2fc56b39682f297b9b27154e87412b99/packages/parent/index.d.ts#L188

If you just delete it, does it fix the problem for you?

**Comment by snelle18** [comment]
I have removed the line and can confirm our build is working. Could you remove the line from your code and publish a new version? Thanks.

**Comment by davidjbradshaw** [comment]
That's really weird, it's been there for six months without anyone else having an issue with it. But I agree that it should probably come out.
